In [41]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout

In [42]:
dataset= pd.read_csv('/Churn_Modelling.csv')
dataset

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [43]:
X = dataset.iloc[:, 3:13]
Y = dataset.iloc[:, 13]
print(X)
print(Y)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1
1             608     Spain  Female   41       1   83807.86              1
2             502    France  Female   42       8  159660.80              3
3             699    France  Female   39       1       0.00              2
4             850     Spain  Female   43       2  125510.82              1
...           ...       ...     ...  ...     ...        ...            ...
9995          771    France    Male   39       5       0.00              2
9996          516    France    Male   35      10   57369.61              1
9997          709    France  Female   36       7       0.00              1
9998          772   Germany    Male   42       3   75075.31              2
9999          792    France  Female   28       4  130142.79              1

      HasCrCard  IsActiveMember  EstimatedSalary
0             1               1        101348.88
1             0               1        112542.58
2             1               0        113931.57
3             0               0         93826.63
4             1               1         79084.10
...         ...             ...              ...
9995          1               0         96270.64
9996          1               1        101699.77
9997          0               1         42085.58
9998          1               0         92888.52
9999          1               0         38190.78

[10000 rows x 10 columns]
0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [44]:
#create dummy variable
geography = pd.get_dummies(X['Geography'],drop_first=True)
gender = pd.get_dummies(X['Gender'],drop_first=True)

In [45]:
#concatenate the dataframes
X = pd.concat([X,geography,gender], axis = 1)
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
0,619,France,Female,42,2,0.00,1,1,1,101348.88,False,False,False
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,False,True,False
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,False,False,False
3,699,France,Female,39,1,0.00,2,0,0,93826.63,False,False,False
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,False,False,True
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,False,False,True
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,False,False,False
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,True,False,True
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,False,False,False

In [46]:
#Drop unnecessary colummns
X = X.drop(["Geography","Gender"], axis = 1)
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
0,619,42,2,0.00,1,1,1,101348.88,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,False,False,False
9998,772,42,3,75075.31,2,1,0,92888.52,True,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,False,False,False

In [47]:
#Split X dataset in to training set and test set
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state =0)
X_test

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
9394,597,35,8,131101.04,1,1,1,192852.67,True,False,False
898,523,40,2,102967.41,1,1,0,128702.10,False,False,False
2398,706,42,8,95386.82,1,1,1,75732.25,False,True,False
5906,788,32,4,112079.58,1,0,0,89368.59,False,False,True
2343,706,38,5,163034.82,2,1,1,135662.17,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...
1037,625,24,1,0.00,2,1,1,180969.55,False,False,False
2899,586,35,7,0.00,2,1,0,70760.69,False,False,False
9549,578,36,1,157267.95,2,1,0,141533.19,False,True,True
2740,650,34,4,142393.11,1,1,1,11276.48,True,False,True
6690,573,30,8,127406.50,1,1,0,192950.60,True,False,True

In [48]:
#Features scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [61]:
#Models and layers
model = Sequential()
# model.add(Dense(units = 6, kernel_initializer = 'he_uniform', activation = 'relu', input_dim = 11))
# model.add(Dense(units = 6, kernel_initializer = 'he_uniform', activation = 'relu'))
model.add(Dense(units = 10, kernel_initializer = 'he_normal', activation = 'relu', input_dim = 11))
model.add(Dropout(0.3))
model.add(Dense(units = 20, kernel_initializer = 'he_normal', activation = 'relu'))
model.add(Dropout(0.4))
model.add(Dense(units = 15, kernel_initializer = 'he_normal', activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(units = 1, kernel_initializer = 'glorot_uniform', activation = 'sigmoid'))

In [62]:
#Compile and fit th data
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.fit(X_train, Y_train, validation_split = 0.33, batch_size = 10, epochs = 100)

Epoch 1/100
536/536 [==============================] - 3s 4ms/step - loss: 0.6576 - accuracy: 0.7208 - val_loss: 0.5078 - val_accuracy: 0.7955
Epoch 2/100
536/536 [==============================] - 2s 3ms/step - loss: 0.5350 - accuracy: 0.7873 - val_loss: 0.4785 - val_accuracy: 0.7955
Epoch 3/100
536/536 [==============================] - 2s 5ms/step - loss: 0.5041 - accuracy: 0.7962 - val_loss: 0.4606 - val_accuracy: 0.7948
Epoch 4/100
536/536 [==============================] - 2s 3ms/step - loss: 0.4829 - accuracy: 0.7992 - val_loss: 0.4455 - val_accuracy: 0.7986
Epoch 5/100
536/536 [==============================] - 2s 3ms/step - loss: 0.4641 - accuracy: 0.8059 - val_loss: 0.4319 - val_accuracy: 0.8031
Epoch 6/100
536/536 [==============================] - 2s 3ms/step - loss: 0.4470 - accuracy: 0.8119 - val_loss: 0.4195 - val_accuracy: 0.8084
Epoch 7/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4463 - accuracy: 0.8072 - val_loss: 0.4133 - val_accuracy: 0.8084
Epoch 8/100
536/536 [==============================] - 2s 3ms/step - loss: 0.4425 - accuracy: 0.8102 - val_loss: 0.4108 - val_accuracy: 0.8088
Epoch 9/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4234 - accuracy: 0.8242 - val_loss: 0.3991 - val_accuracy: 0.8232
Epoch 10/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4071 - accuracy: 0.8304 - val_loss: 0.3911 - val_accuracy: 0.8338
Epoch 11/100
536/536 [==============================] - 3s 5ms/step - loss: 0.4063 - accuracy: 0.8268 - val_loss: 0.3898 - val_accuracy: 0.8285
Epoch 12/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3999 - accuracy: 0.8283 - val_loss: 0.3849 - val_accuracy: 0.8349
Epoch 13/100
536/536 [==============================] - 2s 3ms/step - loss: 0.4036 - accuracy: 0.8294 - val_loss: 0.3880 - val_accuracy: 0.8273
Epoch 14/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3951 - accuracy: 0.8324 - val_loss: 0.3850 - val_accuracy: 0.8243
Epoch 15/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3904 - accuracy: 0.8356 - val_loss: 0.3820 - val_accuracy: 0.8323
Epoch 16/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3901 - accuracy: 0.8281 - val_loss: 0.3813 - val_accuracy: 0.8357
Epoch 17/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3836 - accuracy: 0.8300 - val_loss: 0.3784 - val_accuracy: 0.8372
Epoch 18/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3858 - accuracy: 0.8369 - val_loss: 0.3827 - val_accuracy: 0.8266
Epoch 19/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3858 - accuracy: 0.8375 - val_loss: 0.3828 - val_accuracy: 0.8247
Epoch 20/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3812 - accuracy: 0.8391 - val_loss: 0.3788 - val_accuracy: 0.8315
Epoch 21/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3787 - accuracy: 0.8405 - val_loss: 0.3754 - val_accuracy: 0.8395
Epoch 22/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3833 - accuracy: 0.8416 - val_loss: 0.3806 - val_accuracy: 0.8258
Epoch 23/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3848 - accuracy: 0.8356 - val_loss: 0.3784 - val_accuracy: 0.8360
Epoch 24/100
536/536 [==============================] - 2s 5ms/step - loss: 0.3750 - accuracy: 0.8406 - val_loss: 0.3758 - val_accuracy: 0.8436
Epoch 25/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3790 - accuracy: 0.8391 - val_loss: 0.3777 - val_accuracy: 0.8326
Epoch 26/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3738 - accuracy: 0.8444 - val_loss: 0.3749 - val_accuracy: 0.8368
Epoch 27/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3777 - accuracy: 0.8382 - val_loss: 0.3835 - val_accuracy: 0.8190
Epoch 28/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3769 - accuracy: 0.8388 - val_loss: 0.3801 - val_accuracy: 0.8190
Epoch 29/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3673 - accuracy: 0.8425 - val_loss: 0.3781 - val_accuracy: 0.8220
Epoch 30/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3703 - accuracy: 0.8421 - val_loss: 0.3734 - val_accuracy: 0.8376
Epoch 31/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3704 - accuracy: 0.8423 - val_loss: 0.3740 - val_accuracy: 0.8360
Epoch 32/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3682 - accuracy: 0.8451 - val_loss: 0.3761 - val_accuracy: 0.8273
Epoch 33/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3699 - accuracy: 0.8451 - val_loss: 0.3740 - val_accuracy: 0.8330
Epoch 34/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3619 - accuracy: 0.8496 - val_loss: 0.3719 - val_accuracy: 0.8395
Epoch 35/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3707 - accuracy: 0.8453 - val_loss: 0.3695 - val_accuracy: 0.8410
Epoch 36/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3669 - accuracy: 0.8451 - val_loss: 0.3759 - val_accuracy: 0.8262
Epoch 37/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3689 - accuracy: 0.8438 - val_loss: 0.3696 - val_accuracy: 0.8432
Epoch 38/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3710 - accuracy: 0.8434 - val_loss: 0.3706 - val_accuracy: 0.8395
Epoch 39/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3675 - accuracy: 0.8416 - val_loss: 0.3694 - val_accuracy: 0.8436
Epoch 40/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3679 - accuracy: 0.8421 - val_loss: 0.3726 - val_accuracy: 0.8372
Epoch 41/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3656 - accuracy: 0.8475 - val_loss: 0.3695 - val_accuracy: 0.8413
Epoch 42/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3656 - accuracy: 0.8410 - val_loss: 0.3734 - val_accuracy: 0.8311
Epoch 43/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3668 - accuracy: 0.8489 - val_loss: 0.3766 - val_accuracy: 0.8254
Epoch 44/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3660 - accuracy: 0.8498 - val_loss: 0.3700 - val_accuracy: 0.8432
Epoch 45/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3649 - accuracy: 0.8492 - val_loss: 0.3715 - val_accuracy: 0.8364
Epoch 46/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3667 - accuracy: 0.8419 - val_loss: 0.3724 - val_accuracy: 0.8342
Epoch 47/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3649 - accuracy: 0.8431 - val_loss: 0.3720 - val_accuracy: 0.8364
Epoch 48/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3696 - accuracy: 0.8464 - val_loss: 0.3733 - val_accuracy: 0.8357
Epoch 49/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3694 - accuracy: 0.8462 - val_loss: 0.3732 - val_accuracy: 0.8323
Epoch 50/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3646 - accuracy: 0.8489 - val_loss: 0.3692 - val_accuracy: 0.8417
Epoch 51/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3597 - accuracy: 0.8483 - val_loss: 0.3698 - val_accuracy: 0.8372
Epoch 52/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3612 - accuracy: 0.8464 - val_loss: 0.3671 - val_accuracy: 0.8395
Epoch 53/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3672 - accuracy: 0.8466 - val_loss: 0.3686 - val_accuracy: 0.8387
Epoch 54/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3693 - accuracy: 0.8470 - val_loss: 0.3674 - val_accuracy: 0.8406
Epoch 55/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3569 - accuracy: 0.8546 - val_loss: 0.3668 - val_accuracy: 0.8429
Epoch 56/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3635 - accuracy: 0.8442 - val_loss: 0.3675 - val_accuracy: 0.8406
Epoch 57/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3670 - accuracy: 0.8470 - val_loss: 0.3667 - val_accuracy: 0.8444
Epoch 58/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3630 - accuracy: 0.8490 - val_loss: 0.3700 - val_accuracy: 0.8368
Epoch 59/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3679 - accuracy: 0.8457 - val_loss: 0.3693 - val_accuracy: 0.8357
Epoch 60/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3689 - accuracy: 0.8477 - val_loss: 0.3736 - val_accuracy: 0.8307
Epoch 61/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3673 - accuracy: 0.8477 - val_loss: 0.3691 - val_accuracy: 0.8459
Epoch 62/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3656 - accuracy: 0.8475 - val_loss: 0.3691 - val_accuracy: 0.8417
Epoch 63/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3660 - accuracy: 0.8487 - val_loss: 0.3662 - val_accuracy: 0.8440
Epoch 64/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3547 - accuracy: 0.8503 - val_loss: 0.3648 - val_accuracy: 0.8459
Epoch 65/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3655 - accuracy: 0.8470 - val_loss: 0.3684 - val_accuracy: 0.8398
Epoch 66/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3667 - accuracy: 0.8453 - val_loss: 0.3721 - val_accuracy: 0.8281
Epoch 67/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3631 - accuracy: 0.8475 - val_loss: 0.3644 - val_accuracy: 0.8482
Epoch 68/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3607 - accuracy: 0.8487 - val_loss: 0.3700 - val_accuracy: 0.8360
Epoch 69/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3692 - accuracy: 0.8477 - val_loss: 0.3667 - val_accuracy: 0.8395
Epoch 70/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3619 - accuracy: 0.8472 - val_loss: 0.3650 - val_accuracy: 0.8444
Epoch 71/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3594 - accuracy: 0.8490 - val_loss: 0.3659 - val_accuracy: 0.8406
Epoch 72/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3626 - accuracy: 0.8457 - val_loss: 0.3649 - val_accuracy: 0.8425
Epoch 73/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3617 - accuracy: 0.8462 - val_loss: 0.3662 - val_accuracy: 0.8395
Epoch 74/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3673 - accuracy: 0.8487 - val_loss: 0.3643 - val_accuracy: 0.8451
Epoch 75/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3676 - accuracy: 0.8457 - val_loss: 0.3669 - val_accuracy: 0.8402
Epoch 76/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3619 - accuracy: 0.8522 - val_loss: 0.3652 - val_accuracy: 0.8432
Epoch 77/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3619 - accuracy: 0.8502 - val_loss: 0.3695 - val_accuracy: 0.8379
Epoch 78/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3546 - accuracy: 0.8483 - val_loss: 0.3663 - val_accuracy: 0.8448
Epoch 79/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3666 - accuracy: 0.8487 - val_loss: 0.3704 - val_accuracy: 0.8326
Epoch 80/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3618 - accuracy: 0.8526 - val_loss: 0.3692 - val_accuracy: 0.8349
Epoch 81/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3590 - accuracy: 0.8481 - val_loss: 0.3663 - val_accuracy: 0.8413
Epoch 82/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3653 - accuracy: 0.8490 - val_loss: 0.3713 - val_accuracy: 0.8353
Epoch 83/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3669 - accuracy: 0.8483 - val_loss: 0.3669 - val_accuracy: 0.8387
Epoch 84/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3596 - accuracy: 0.8515 - val_loss: 0.3655 - val_accuracy: 0.8463
Epoch 85/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3627 - accuracy: 0.8511 - val_loss: 0.3668 - val_accuracy: 0.8402
Epoch 86/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3553 - accuracy: 0.8528 - val_loss: 0.3632 - val_accuracy: 0.8478
Epoch 87/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3630 - accuracy: 0.8485 - val_loss: 0.3659 - val_accuracy: 0.8413
Epoch 88/100
536/536 [==============================] - 3s 6ms/step - loss: 0.3609 - accuracy: 0.8526 - val_loss: 0.3664 - val_accuracy: 0.8425
Epoch 89/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3633 - accuracy: 0.8505 - val_loss: 0.3660 - val_accuracy: 0.8391
Epoch 90/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3642 - accuracy: 0.8479 - val_loss: 0.3641 - val_accuracy: 0.8482
Epoch 91/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3674 - accuracy: 0.8457 - val_loss: 0.3651 - val_accuracy: 0.8429
Epoch 92/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3587 - accuracy: 0.8505 - val_loss: 0.3677 - val_accuracy: 0.8395
Epoch 93/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3624 - accuracy: 0.8503 - val_loss: 0.3671 - val_accuracy: 0.8368
Epoch 94/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3609 - accuracy: 0.8498 - val_loss: 0.3663 - val_accuracy: 0.8402
Epoch 95/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3592 - accuracy: 0.8511 - val_loss: 0.3685 - val_accuracy: 0.8349
Epoch 96/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3579 - accuracy: 0.8483 - val_loss: 0.3645 - val_accuracy: 0.8470
Epoch 97/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3620 - accuracy: 0.8485 - val_loss: 0.3674 - val_accuracy: 0.8364
Epoch 98/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3665 - accuracy: 0.8449 - val_loss: 0.3701 - val_accuracy: 0.8307
Epoch 99/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3622 - accuracy: 0.8477 - val_loss: 0.3669 - val_accuracy: 0.8395
Epoch 100/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3621 - accuracy: 0.8492 - val_loss: 0.3640 - val_accuracy: 0.8444

In [63]:
#predicting the test set result
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred

63/63 [==============================] - 0s 2ms/step

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [64]:
#confusion matrics
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,y_pred)
cm

array([[1579,   16],
       [ 271,  134]])

In [65]:
#Calculate the accuracy score
from sklearn.metrics import accuracy_score
score = accuracy_score(Y_test,y_pred)
score

0.8565